### ISSUE TITLE
Cannot Install on Google Colab

### ISSUE THREAD

**Issue by soulspark666** [TianZerL/pyanime4k#2]
I was trying to install this on google colab notebook, but it shows the following error:
```
Collecting pyanime4k
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement pyanime4k (from versions: )
No matching distribution found for pyanime4k
```
The command I used to install it was:
```
python3.8 -m pip install pyanime4k
```
pip version used (python3.8 -m pip --version)
```
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.8)
```
Python version used:
```
Python 3.8.3
```
I used the above commands since colab has python(3.6) and pip(pip 19.3.1) already installed.
I used the [following](https://linuxize.com/post/how-to-install-python-3-8-on-ubuntu-18-04/) guide to install python3.8 and associated pip.

**Comment by TianZerL** [comment]
pyanime4k only provides the pre-build binary for Windows x64.

**Comment by TianZerL** [comment]
It is difficult to provide a general dynamic link library for Linux, if you want to use anime4k in Linux, please consider anime4kcpp directly.

**Comment by soulspark666** [comment]
ok since it cannot be used on Linux, I will now close this issue

**Comment by soulspark666** [comment]
Hey, could add it as an enhancement, to get it working on Linux!

**Comment by TianZerL** [comment]
pyanime4k now supports Linux by manually installing, the newest version are not upload to pypi yet.

**Comment by TianZerL** [comment]
After countless attempts, I finally launched a Linux version(For most Linux, oldest tested in Ubuntu14.04) that can be installed directly through pip, you can try it. (If you want to run it in a server without graphical interface, you may need install libgtk2.0 first)
```
sudo apt install libgtk2.0
pip3 install pyanime4k
```

**Comment by jcklpe** [comment]
@TianZerL  Thank you! this is awesome!

**Comment by jcklpe** [comment]
@TianZerL  actually I'm having a bit of trouble. I install it from pip no problem but when I try to run it import it to script it crashes the runtime.   
  
Here's what the google colab logs say:  
 

<table><tbody><tr><td colspan="1">Jul 8, 2020, 11:40:56 PM</td><td colspan="1">WARNING</td><td colspan="1">WARNING:root:kernel 6bd64ed4-2e6b-48c5-a170-5b080196016d restarted</td></tr><tr><td colspan="1">Jul 8, 2020, 11:40:56 PM</td><td colspan="1">INFO</td><td colspan="1">KernelRestarter: restarting kernel (1/5), keep random ports</td></tr><tr><td colspan="1">Jul 8, 2020, 11:40:56 PM</td><td colspan="1">WARNING</td><td colspan="1">src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f26e9304ba0&nbsp;</td></tr><tr><td colspan="1">Jul 8, 2020, 11:37:47 PM</td><td colspan="1">WARNING</td><td colspan="1">WARNING:root:kernel 6bd64ed4-2e6b-48c5-a170-5b080196016d restarted</td></tr><tr><td colspan="1">Jul 8, 2020, 11:37:47 PM</td><td colspan="1">INFO</td><td colspan="1">KernelRestarter: restarting kernel (1/5), keep random ports</td></tr><tr><td colspan="1">Jul 8, 2020, 11:37:46 PM</td><td colspan="1">WARNING</td><td colspan="1">src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7fe2a1a9aba0&nbsp;</td></tr><tr><td colspan="1">Jul 8, 2020, 11:36:55 PM</td><td colspan="1">INFO</td><td colspan="1">Uploading file to /content/basq1.jpg</td></tr><tr><td colspan="1">Jul 8, 2020, 11:32:53 PM</td><td colspan="1">WARNING</td><td colspan="1">WARNING:root:kernel 6bd64ed4-2e6b-48c5-a170-5b080196016d restarted</td></tr><tr><td colspan="1">Jul 8, 2020, 11:32:53 PM</td><td colspan="1">INFO</td><td colspan="1">KernelRestarter: restarting kernel (1/5), keep random ports</td></tr><tr><td colspan="1">Jul 8, 2020, 11:32:50 PM</td><td colspan="1">WARNING</td><td colspan="1">src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f3a752c4ba0&nbsp;</td></tr></tbody></table>

**Comment by TianZerL** [comment]
@jcklpe

> Attempt to free invalid pointer 0x7f26e9304ba0 

pyanime4k will free the C pointer of Anime4KCore after using, it is working normally on local Linux environment. I guess there is something different about memory management of jupty notebook environment, which caused this.   

Maybe you need to delete the `__del__` of class `AC` in `ac.py`, I am not sure if there will be a memory leak, but it's worth a try.

**Comment by TianZerL** [comment]
@jcklpe
I just tried it on google colab, as I suspected, run it by `python3 src.py` was all normal, but crashed by jupty notebook.  
It should be caused by a memory management policy of jupty notebook.

**Comment by jcklpe** [comment]
I'm a little new to python stuff. The src.py file would be in whatever package location pip installs to right?

**Comment by jcklpe** [comment]
@TianZerL  Just checked the pip install location on colab, and I don't see a src.py file, nor do I see one in the git repo. Sorry, like I said, I'm new to python and maybe I'm missing something really obvious. I can successfully run `!python3 /usr/local/lib/python3.6/dist-packages/pyanime4k/__init__.py` but I don't know how to import to the project so that I can just use the pyanime4k functions as part of my larger script.

**Comment by TianZerL** [comment]
@jcklpe
`src.py` means a script that you wrote, it could be any name you like.    
what i mean  is don't not use jupty notebook to run a python code but use `python3`.  
for eaxamle:
you have code
```
from pyanime4k import ac 

p = ac.AC()
p.list_GPUs()
```
save it to a file named `test.py` and upload it to your google colab, run code
```
!python3 test.py
```
you will see the GPU infomation.

**Comment by jcklpe** [comment]
@TianZerL Ooooh thanks. gotcha.   
  
Yes I can confirm that works. Got to make a weird work around to have it work with the colab project but so far looking good! Thanks!

**Comment by jcklpe** [comment]
@TianZerL   
  
Apologies for bothering again, but perhaps you might know what the issue is here:  
  
I need to run pyanime4k in conjunction with another neural network. Basically I've made [a Google Colab to run neural-style transfer in batch from folder in a Google Drive](https://colab.research.google.com/drive/1YEeWvuCreoIAFnhGRYQTXtF2Tlj0UCiR?usp=sharing). Because of the limitations of neural style transfer outputs I need to upres them using pyanime4k.   
  
This means that I need to be able to access the variables from the neural-style transfer process in the !python script.py   
  
obviously script.py doesn't have access to variables declared in the notebook environment so I came up with a way to programmatically create a script.py file and then inject the variables from the notebook process and then run that script using !python so that it wouldn't crash  
  
[Here's a link to the colab notebook that I'm trying stuff out on.](https://colab.research.google.com/drive/1rRg3ul3sSDgSYGgplOYPOvZ47WqXd80A?usp=sharing)   
  
Here's a basic test: 

```
testVar = '682.jpg'
importStatement = "import pyanime4k, os, pathlib\n"
imageStatement = f"image = [ pathlib.Path('{testVar}') ] \n"
scriptStatement = f"pyanime4k.upscale_images(input_paths= '{testVar}', output_path= pathlib.Path('/content/output'))"

scriptFile= open("script.py", "w")
scriptFile.write(f"{importStatement}{imageStatement}{scriptStatement}")
scriptFile.close()
!python script.py
```

and I get the following type error:

```
Traceback (most recent call last):
 File "script.py", line 3, in <module>
   pyanime4k.upscale_images(input_paths= '682.jpg', output_path= pathlib.Path('/content/output'))
 File "/usr/local/lib/python3.6/dist-packages/pyanime4k/upscale.py", line 149, in upscale_images
   (path.stem + output_suffix, path.suffix)
 File "/usr/lib/python3.6/pathlib.py", line 899, in __truediv__
   return self._make_child((key,))
 File "/usr/lib/python3.6/pathlib.py", line 686, in _make_child
   drv, root, parts = self._parse_args(args)
 File "/usr/lib/python3.6/pathlib.py", line 640, in _parse_args
   a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not tuple
```

If I replace the `pathlib.Path('/content/output')` with the string `'/content/output'` I get instead an error `AttributeError: 'str' object has no attribute 'exists'`    
  
I've done a bunch of googling and fiddling around with different approaches but I can't seem to crack what the issue is here?  
  
I also looked at git cloning anime4kCCP and then building it on the notebook, but the cmake version needed to be 3.15 instead of 3.12 and then that meant downloading cmake and uploading it to the colab notebook but at that point, the process isn't very script oriented, and I'm trying to keep everything purely script oriented so that I can distribute the resulting co-lab to other artists who are less technically inclined than me.

**Comment by TianZerL** [comment]
@TianZerL 
It do have some problems of the high level API, I will fixed it soon. High level API have another one to maintain it, and I didn't test it strictly after updating, please use AC class temporarily. See the examples in readme.

**Comment by TianZerL** [comment]
@jcklpe
I have fixed it, please upgrade pyanime4k by pip.

**Comment by jcklpe** [comment]
@TianZerL  Thanks! Works like a charm!

**Comment by TianZerL** [comment]
@jcklpe 
I've solved the crash problem on Google Colab, please do not use the pip version, use shell script to build it, see [here](https://github.com/TianZerL/pyanime4k#shell-script).

**Comment by jcklpe** [comment]
thank you @TianZerL !
