### ISSUE TITLE
install by pip in anaconda's virtual env (windows), raise this error when importing

### ISSUE THREAD

**Issue by L1Uc** [TianZerL/pyanime4k#5]
>>> import pyanime4k
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\***\Anaconda3\envs\mpegtorch\lib\site-packages\pyanime4k\__init__.py", line 9, in <module>
    import pyanime4k.error
  File "C:\Users\***\Anaconda3\envs\mpegtorch\lib\site-packages\pyanime4k\error.py", line 9, in <module>
    from pyanime4k.wrapper import *
  File "C:\Users\***\Anaconda3\envs\mpegtorch\lib\site-packages\pyanime4k\wrapper\__init__.py", line 9, in <module>
    from pyanime4k.wrapper.acwrapper import *
  File "C:\Users\***\Anaconda3\envs\mpegtorch\lib\site-packages\pyanime4k\wrapper\acwrapper.py", line 22, in <module>
    os.path.join(curr_path, ac_lib[platform.system()]))
  File "C:\Users\***\Anaconda3\envs\mpegtorch\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\***\Anaconda3\envs\mpegtorch\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

python 3.7.2

**Comment by TianZerL** [comment]
In old version of python(<3.8), you need add dll libs `(C:\Users*\Anaconda3\envs\mpegtorch\lib\site-packages\pyanime4k\wrapper\) ` to PATH environment variables.

**Comment by TianZerL** [comment]
I have fixed it, please upgrade pyanime4k by pip.

**Comment by L1Uc** [comment]
I have upgraded pyanime4k but the problem still appears

**Comment by TianZerL** [comment]
v2.2.7？

**Comment by L1Uc** [comment]
![image](https://user-images.githubusercontent.com/25033607/87151990-6f5fba80-c2e7-11ea-842e-c3e12e350eca.png)

**Comment by TianZerL** [comment]
please try to add dll libs (C:\Users*\Anaconda3\envs\mpegtorch\lib\site-packages\pyanime4k\wrapper\) to PATH environment variables, if not work, please install vc runtime 2017

**Comment by TianZerL** [comment]
Are you running in a local environment or on a server?

**Comment by L1Uc** [comment]
local environment
and i'm trying to install vc runtime

**Comment by L1Uc** [comment]
![image](https://user-images.githubusercontent.com/25033607/87154242-77b9f480-c2eb-11ea-9a8a-94d1d89d3d6d.png)
is this right?

**Comment by TianZerL** [comment]
yes, it is

**Comment by L1Uc** [comment]
I have installed it, but the problem still appears...

**Comment by TianZerL** [comment]
This problems is beacuse of missing dlls, I don't think there are something still missing. Try to use Python3.8. And what's your video card, some old card doesn't support OpenCL will get this problem too.

**Comment by L1Uc** [comment]
My video card is Nvidia 1070. Seems using python 3.8 is the only way

**Comment by TianZerL** [comment]
I tested v2.2.6 in python3.7.7, got same problem and fixed it, now everything worked fine, so I'm not sure what's going on now.

**Comment by L1Uc** [comment]
conda create -n your_env_name python=X.X

**Comment by L1Uc** [comment]
Maybe it's because I installed vs2017 and vs2015? How did you fix it? Installing vc runtime?

**Comment by TianZerL** [comment]
No, I added the dll folder to `os.environ['PATH']`, same as adding system environment variables.

**Comment by TianZerL** [comment]
I just tested it in anaconda with python3.7.7 with pyanime4k v2.2.7,  everything worked fine.

**Comment by L1Uc** [comment]
Fine, maybe my system has some unknown problems.

**Comment by L1Uc** [comment]
I successfully run it in Ubuntu.
